### ISSUE TITLE
Virus alert PUA:Win32/Presenoker

### ISSUE THREAD

**Issue by lsalamon** [PhoenixMinerDevTeam/files#1]
Why the Windows version PhoenixMiner_5.2e_Windows.zip that I downloaded accuses the presence of PUA:Win32/Presenoker detected by Microsoft Defender Antivirus?

**Comment by UselessGuru** [comment]
Most mining SW is seen as malicious by AV software. Either trust the developer or don't use the miner SW.

**Comment by PhoenixMinerDevTeam** [comment]
Ever since the first release of our miner, various AV scanners "discovered" a lot of threats in an absolutely clean executable (built from entirely our source, without any external "blobs", so we knew it was totally clean). For a while we tried to argue with them, and several of the major ones made exceptions in their databases. However we soon discovered that we will need to go through this with each new release, which is a totally unproductive use of our time. 

We don't even use full executable encryption like some of our competitors - just some (admittedly advanced) anti-tampering code to protect our IP and detect attempts to reverse-engineer parts of our software. So, our choice is to either bow to the AV makers and make our software easy to reverse and lose our competitive advantage, or ignore them and provide the end users with the necessary tools (e.g. checksums, public key, signature files, etc.) to check the authenticity of our software.
